### ISSUE TITLE
Module doesn't not work. Missing from module setting. 

### ISSUE THREAD

**Issue by NashWise** [FLPub/symbaroum5ecore#14]
```
import-dialog.js:244 Uncaught TypeError: Cannot set property migrationData of class ModuleImportDialog extends Dialog {

  /* Default class data for overrides */
  static get moduleName() {...<omitted>...
} which has only a getter
    at Function.<static_initializer> (import-dialog.js:244:26)
    at import-dialog.js:9:41
```

This is the only error reporting in the console.

**Comment by NashWise** [comment]
Turns out that it's related to OperaGX. It seems that the module only works with Chromium browser. Eitherway I would thanked Honeybadger for helping me on troubleshooting the bug.

**Comment by NashWise** [comment]
Oh yeah it's not OperaGX, it's pop up blocker that prevents the module from downloading.

**Comment by trioderegion** [comment]
Thanks for closing the loop on this!
