### ISSUE TITLE
Showing Journal after Import Errors

### ISSUE THREAD

**Issue by trioderegion** [FLPub/symbaroum5ecore#23]
On v10p1, `mattexdee` noticed the following error after import, when the journal entry is supposed to be shown -- for any module using the core importer class (i.e. all RoS 5e modules).

```
foundry.js:44661 Uncaught Error: TypeError: Cannot read properties of undefined (reading 'show')
    at Dialog.submit (foundry.js:44661:13)
    at Dialog._onClickButton (foundry.js:44620:10)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (jquery.min.js:2:41048)
```

**Comment by pwatson100** [comment]
I have seen that in the past when the journal entry has not been imported???

**Comment by trioderegion** [comment]
Likely just a small API change introduced in v10. For the moment, we do not need to concern ourselves with this -- simply tracking for when the time is right.

**Comment by trioderegion** [comment]
Closed in Beta 1
