### ISSUE TITLE
Captain/Warrior Fighting Style missing items

### ISSUE THREAD

**Issue by Koltak** [FLPub/symbaroum5ecore#26]
The Player's Guide "Fighting Style" item seems to be missing the entries for "Polearm Fighting", "Shield Fighting" and "Snare Fighting".
![grafik](https://user-images.githubusercontent.com/16560380/160909153-1154fdf3-bace-4c00-9754-d620a246e4e9.png)

**Comment by trioderegion** [comment]
This has been addressed in the upcoming Player's Guide update.  Thank you for pointing it out 😄 , please continue to do so.
