### ISSUE TITLE
Tracking Spells

### ISSUE THREAD

**Issue by 19Dawgmeat** [FLPub/symbaroum5ecore#29]
Would it be possible to set up a functionality for the Symbarium character sheet to make it easily identifiable what spells a PC has prepared?  Additionally, spell slots usage to make it more cross compatible traditional 5e ruleset?

**Comment by trioderegion** [comment]
Unless I am mistaken, all spellcasters in symbaroum 5e are "known" casters. Which means they do not need to prepare or track their prepared spells.

To switch back to the core 5e rules (spell slots and prepared spells), simply change the sheet type back to the core sheet (or another 5e sheet module) at the top of your actor sheet window.

**Comment by trioderegion** [comment]
Does this resolve this issue? Can this ticket be closed?

**Comment by 19Dawgmeat** [comment]
Sorta.  I was looking to use the rest rules on the symbaroum character sheet just not the corruption mechanic but I found a workaround.  We can close the ticket.
