### ISSUE TITLE
Resource consumption not working

### ISSUE THREAD

**Issue by Nieeeb** [FLPub/symbaroum5ecore#30]
When attacking with a weapon, such as a bow, it does not consume ammo when attacking. Changing the sheet to the default 5e one and doing nothing else fixes the issue and the weapon consumes ammo as expected.

**Comment by trioderegion** [comment]
Any errors in the console and any non-core roller modules in use?

**Comment by trioderegion** [comment]
confirmed

**Comment by trioderegion** [comment]
https://github.com/FLPub/symbaroum5ecore/blob/79d5d4be5236afae94885e7499b1841d3bd72243/scripts/modules/spellcasting.js#L279

TODO: remove resource object from return value.
