### ISSUE TITLE
Armor properties do not stay selected

### ISSUE THREAD

**Issue by dirusulixes** [FLPub/symbaroum5ecore#31]
fvtt 9.269
D&D5e 1.6.1
symbaroum5ecore 1.0.3
No other modules loaded

Armor properties injected into the 5e item sheet by the module do not stay selected.

https://user-images.githubusercontent.com/5693623/168912585-b91a3a1a-7b7f-4b51-8c96-91ab3cce56f1.mp4

**Comment by trioderegion** [comment]
Thank you for the report, I'll get this and another couple issues fixed up this week 👍
