### ISSUE TITLE
Actor update fails in DnD5e 1.6.2

### ISSUE THREAD

**Issue by bithir** [FLPub/symbaroum5ecore#36]
Unsure if it is known
Symbaroum5ecore v1.0.4

Changing attributes spits out the following in the console - see screenshot:
![image](https://user-images.githubusercontent.com/19734037/172072596-1db3acf5-fce6-4f77-8d7d-ba808be1c3d0.png)

**Comment by dirusulixes** [comment]
I was about to report the same issue. Confirmed for me with DND5e 1.6.2, fvtt 9.269 and no other modules loaded.

**Comment by Nieeeb** [comment]
Can confirm. Cant equip or unequip items when the Symbar sheet is used.

**Comment by trioderegion** [comment]
Fixed in 1.0.5
