### ISSUE TITLE
Spells in magic items cannot be cast

### ISSUE THREAD

**Issue by dirusulixes** [FLPub/symbaroum5ecore#39]
fvtt 9.269
symbaroum5e 1.0.6
magic items 2.2.1

using the DnD5e default character sheet the spells that are added to the spellbook by a magic item using the magic items module can be cast without issue. With the symbaroum5e sheet however an error is thrown:

```
magicitem.js:958 Uncaught (in promise) Error: The key 1mR2enMj6ZzPfobv does not exist in the EmbeddedCollection Collection
    at EmbeddedCollection.get (collection.mjs:106:13)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:10186:30)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:10152:33)
    at ClientDatabaseBackend.update (backend.mjs:153:31)
    at async Item5e.updateDocuments (document.mjs:373:21)
    at async Item5e.update (document.mjs:456:21)
    at async Item5e.roll (entity.js:704:54)
    at async proceed (magicitem.js:947:28)
get @ collection.mjs:106
_preUpdateDocumentArray @ foundry.js:10186
_updateEmbeddedDocuments @ foundry.js:10152
update @ backend.mjs:153
await in update (async)
(anonymous) @ magicitem.js:964
callback @ magicitem.js:873
submit @ foundry.js:44156
_onClickButton @ foundry.js:44119
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

I've done some minimal digging and it seems to happen when the document is updated as part of the corruption calculations.

**Comment by trioderegion** [comment]
You would be correct yet again. Thanks for the report. It concerns the following line:
https://github.com/FLPub/symbaroum5ecore/blob/ffa3a0b51d6356d6bfc31ed51b76c589de8b97bf/scripts/modules/spellcasting.js#L327

The previous fix for a null ID from argon HUD is apparently not robust enough if I'm being passed a compendium document. I can get to this next week hopefully.

However, if you are so inclined, a small PR with a check to see if this is an item owned by the character using it and returning an empty update similar to an item with a null ID, I would be able to readily accept it and release 😄 .

It will be taken care of regardless, thanks *again* for your continued and helpful reports.

**Comment by trioderegion** [comment]
After digging through the Magic Item module and how it works, I cannot figure out a good way to determine if this is a "fake" item provided by the Magic Items module, or a real item rolling normally.

This issue is blocked until I can make this determination, resulting in Magic Items being incompatible with Symbaroum 5e until resolved...

**Comment by trioderegion** [comment]
With the magic items module being rewritten and/or superseded, I am going to close this issue.
