### ISSUE TITLE
[Feature Suggestion] Add option to disable changes to journal formatting

### ISSUE THREAD

**Issue by Nieeeb** [FLPub/symbaroum5ecore#40]
While the new backgrounds and title backdrops look great, they often cause issues with other modules, such as obscuring information. An option to restore the default look would be much appreciated if it's at all possible.

**Comment by pwatson100** [comment]
What modules specifically are you seeing an issue with when using journals and can you give an example please?    I should be able to add an option to remove the journal border and background so it looks like the default.

**Comment by Nieeeb** [comment]
Sure thing. As an example, here's what a lot of the Monk's Enhanced Journals look like. The only difference between the images is the Symbar module being enabled. The title bar blocks the top text fields. Along with that, the "Player Purchasing" and "Player Selling" dropdown menus no longer appear with Symbar installed.

With Module
![withmodule](https://user-images.githubusercontent.com/39679072/177181079-28a1ca87-56e8-481d-8642-c98ffb8e6d5f.png)

Without module
![withoutmodule](https://user-images.githubusercontent.com/39679072/177181043-f9086e0f-e77a-4ad2-b29e-002801a9a135.png)

**Comment by pwatson100** [comment]
Many thanks I will investigate.   That formatting should not be bleeding into Monks Journal.

**Comment by Nieeeb** [comment]
Thank you for your time

**Comment by pwatson100** [comment]
I think I have found the cure for this.  @trioderegion I have pushed the css change to my branch.  Could you check it out with and without Monks Journal enabled when you have a chance please.

**Comment by trioderegion** [comment]
![image](https://user-images.githubusercontent.com/14878515/180030133-6bab00dc-3851-4a80-9bcd-b1c10778cabd.png)

@pwatson100 expected rendering? Looks like the height adjustment is in effect.

**Comment by pwatson100** [comment]
Yes, That, is how it should look.  It had a max-height tag on the h2 so was spilling over on to the field below.
