### ISSUE TITLE
`Update check timed out` on update

### ISSUE THREAD

**Issue by Kayne** [FLPub/symbaroum5ecore#44]
<img width="293" alt="Zrzut ekranu 2022-09-1 o 08 48 45" src="https://user-images.githubusercontent.com/1120451/187849957-f874418b-758c-4b44-9af7-907e3e45086a.png">

On update there is error `Update check timed out`. Currently on version 1.0.7, Foundry latest V9.

**Comment by trioderegion** [comment]
version 1.0.7 is the closing version for Foundry v9. I am not 100% sure why the update check is timing out, but in this case, there is no newer version to grab for v9.
