### ISSUE TITLE
Cannot import modules content

### ISSUE THREAD

**Issue by Milmino** [FLPub/symbaroum5ecore#48]

**Comment by Milmino** [comment]
When first installing module, or attempting to re-run module initial import the following error(s) appear:

Scene[G0AuzIKDRyg5wUDf] Model Validation Errors [Scene.titles]: Model Validation Errors [BaseTile.width]: may not be null [BaseTile.height]: may not be null [Scene.walls]: Model Validation Errors Model Validation Errors [BaseWall.e]: must be a length 4 array of integer coordinates

JournalEntry [0IuGW0IomahIDAY9] Model Validation Errors [JournalEntry.pages]: Model Validation Errors [Base.JournalEntryPage.name]: may not be a blank string.

Then when I click okay, another error appears: 

TypeError: Cannot read properties of undefined (reading 'show')

![Issue1](https://user-images.githubusercontent.com/88582505/196303947-082df5a1-5ffc-4a9d-ad8c-4cc29190dad8.png)

![Issue2](https://user-images.githubusercontent.com/88582505/196304604-674f9534-10d5-44e3-bbd7-122a91d60921.png)

I have other issues with casting magic spells also, as an error appears whenever a player casts a spell. 

Symboroum 5E Ruins of Symbaroum - Core System | ERROR| SY
![issue3]

(https://user-images.githubusercontent.com/88582505/196304801-75c12a3a-2e3f-48bb-a9e8-01294a86ff89.png)
B5E.Error.HTMLParse.

**Comment by trioderegion** [comment]
What versions of dnd5e, foundry, and symbaroum5ecore are in use?

**Comment by rfreeman** [comment]
I have the same issue. Ruins of Symbaroum 5E - Core: 2.0.1, Foundry VTT v10 288, dnd5e 2.0.3. Clean Foundry data install.

**Comment by pwatson100** [comment]
The v10 versions of the modules have not been released yet.   We are doing some testing and hopefully they will be out soon.
