### ISSUE TITLE
Bugs: Import dialog, CS Layout, CS Fonts

### ISSUE THREAD

**Issue by jpwhale** [FLPub/symbaroum5ecore#5]
Some initial findings.

![Chromium_Character_Sheet](https://user-images.githubusercontent.com/60820258/157080316-e015f5f5-bf59-4249-ae15-2a6fdfe577f6.jpg)
![Firefox_Character_Sheet](https://user-images.githubusercontent.com/60820258/157080413-b2088732-2643-4dd3-a5fe-6243bcf5f0ab.jpg)

Foundry Virtual Desktop Version 9, Build 255
DnD5e - Fifth Edition System 1.5.7

**Browser 1:** Chromium 99.0.4844.51
**Browser 2:** Firefox 97.0.2

### Import Dialogue
**Browser 1** and **Browser 2**: Reappears at every login.

### Character Sheet
**Browser 1:** No background image
**Browser 1:** No Window Decoration
**Browser 2:** "Attributes" extends beyond left border partially hiding the A

### Fonts/CSS
**Movement:** Number *and* "FT" are Modesto Condensed
**Initiative:** Number is Modesto Condensed
**Hit Dice:** Number (Remaining Hit Dice) and Number (Total Hit Dice) are Modesto Condensed
**Death Save:** Checkmark and X are Font Awesome (maybe not a bug)
**Resource 1/2/3:** Text over SR and LR click box is SignikaRegular (maybe not a bug)
**Attribute Modifiers**: Both Modifier and Saving Throm number for each Attribute are Modesto Condensed
**Experience Points:** Number indicating Next Level is Modesto Condensed

**Comment by pwatson100** [comment]
Thank you for the feedback. 
Looking at the first two issues based on the image you posted it appears to be set as the DnD5e Default so there are no borders or decoration just the normal 5e character sheet.. 
The third image Ah Firefox!.  I have made the sheet a little wider so it will fit correctly.  
I will look into the font issues you have spotted and correct where I can.

**Comment by pwatson100** [comment]
Font issues: 
Movement: Number and "FT" are Modesto Condensed - Corrected
Initiative: Number is Modesto Condensed - Corrected
Hit Dice: Number (Remaining Hit Dice) and Number (Total Hit Dice) are Modesto Condensed - Corrected
Death Save: Checkmark and X are Font Awesome (maybe not a bug) - Not a bug
Resource 1/2/3: Text over SR and LR click box is SignikaRegular (maybe not a bug) - Not a bug
Attribute Modifiers: Both Modifier and Saving Throm number for each Attribute are Modesto Condensed - Corrected
Experience Points: Number indicating Next Level is Modesto Condensed - Corrected

**Comment by jpwhale** [comment]
> Thank you for the feedback. Looking at the first two issues based on the image you posted it appears to be set as the DnD5e Default so there are no borders or decoration just the normal 5e character sheet.. The third image Ah Firefox!. I have made the sheet a little wider so it will fit correctly. I will look into the font issues you have spotted and correct where I can.

Actually, I specifically selected the Symbaroum 5e Sheet in Chromium, and that's what I took the screenshot of.

**Comment by pwatson100** [comment]
Yes. That is the Symbaroum sheet but with the 5E grey background and black text.  In the drop down it's "Default dnd5e". No frills 5E sheet.
