### ISSUE TITLE
Using Symbaroum 5E system with dnd5E module, causes errors after updates. 

### ISSUE THREAD

**Issue by Sherigan81** [FLPub/symbaroum5ecore#50]
Hello! 

I updated to dnd5e 2.1.2 from 2.0.3 today as we are running it together with the Symbaroum 5E system, unfortunately without creating a backup of the system. While logging back onto foundry i found errors when attempting to open the character sheets. The pinned script took care of most of the errors but one still remain. (I will attach a screenshot of the error log). honeybadger asked that I forwarded the question here, so that you could patch it at a later date.

![error](https://user-images.githubusercontent.com/82651335/212730523-491a6d2c-86ac-4a77-b726-51344bed9f03.jpg)

Thanks in advance

**Comment by muklin** [comment]
I saw this too!  I thought I raised a bug, but now can't find it.

I was able to make it work again by downgrading 5e module back to 2.0.3

**Comment by Sherigan81** [comment]
Did that work for you? I heard it wouldn't so I didnt dare to attempt it.

Den mån 16 jan. 2023 19:14muklin ***@***.***> skrev:

> I saw this too! I thought I raised a bug, but now can't find it.
>
> I was able to make it work again by downgrading 5e module back to 2.0.3
>

**Comment by muklin** [comment]
Yep it worked for me.

I couldn't open pcs, same for my players.  I could open npcs ok.  I
downgraded 5e and it all wnt back to being ok.

**Comment by trioderegion** [comment]
Thanks for the reports. We will address the system upgrade as soon as possible.
