### ISSUE TITLE
Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Mad7eo** [FLPub/symbaroum5ecore#57]
Every time I open my world I see this message

![image](https://github.com/FLPub/symbaroum5ecore/assets/89466389/fe81e0f9-a3ae-4082-8607-2dda42b2a62e)

Then, clicking on Ok this is the error I get

![image](https://github.com/FLPub/symbaroum5ecore/assets/89466389/28f33654-708f-4e83-9aad-e72ad5e10227)

I tried with just RoS Core (v. 3.0.1), Player's Guide (3.0.0), Bestiary (3.0.0) and Gm Guide (3.0.0)
DnD 2.3.1
Foundry v11.313

![image](https://github.com/FLPub/symbaroum5ecore/assets/89466389/1c5f0a55-feb3-480e-9a86-a5ac4267ab2a)

**Comment by trioderegion** [comment]
This was corrected after a clean v11 install.
