### ISSUE TITLE
Ruins of Symbaroum Core is incompatible with D&D 5e 3.0+

### ISSUE THREAD

**Issue by CaiusStarsight** [FLPub/symbaroum5ecore#62]
Due to the release of the new 3.0 rules system, Core is incompatible with the new features, particularly character sheet options like Corruption.

In order that players can use the high quality new 5e features, (and the other common modules that are updating around this huge change) please may RoS Core be updated to be compatible with the new system?

If this is not possible, please may there be a statement about how the module is intended to be upkept, ie is it intended to be left at 5e 2.1 etc and there will be no further updates? This is so that GMs using the system can act accordingly with their update schedule and make sure there will be no breaking changes, or going back and forth on updates.

Many thanks!

**Comment by hellquist** [comment]
+1

For those of us that alternate gaming sessions with both RoS campaigns as well as DnD5 campaigns it turns really complicated  to keep things at a functional state (I honestly don't know how), it will quickly turn very complex to install/un-install things and/or roll-back (and their dependencies) for each gaming session when I actually wish to prep campaigns long in advance.

**Comment by IDDragnil1** [comment]
Update on this ?

**Comment by Veegi** [comment]
Is there any update on this? My group is planning on starting a RoS campaign soon, and it would be great to have support for the D&D5e system updates.

**Comment by trioderegion** [comment]
there is a beta version that gets the module up and running again -- I would appreciate any feedback on issues found. 

https://github.com/FLPub/symbaroum5ecore/releases/tag/4.0%2B1

**Comment by trioderegion** [comment]
Closed by #70
